### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by wyozi** [notcake/vfs#1]
vfs.lua includes glib, but I did not spot any other usages for it than adding vfs files to compressed pack. Would it be possible to use vfs with zero dependencies if I replaced that with normal includes, or are there some other gotchas?

Also, merry Christmas.

**Comment by notcake** [comment]
If you search for "GLib" in the vfs code you'll find most of the references to it.
You'll also need GLib.PlayerMonitor (glib/garrysmod/servers/playermonitor.lua and playermonitorentry.lua) and everything under glib/io and glib/net+glib/garrysmod/net. You might want to rename "GLib" to "VFS" in the code.

You could try experimenting with GLib.CodeExporter, which'll do the replacement for you and dump the files in a folder you can specify under your data folder: http://pastebin.com/vvnzuQwg
